### ISSUE TITLE
Setup media queries

### ISSUE THREAD

**Issue by LionOnTheWeb** [hasshdigital/aricha_2018#2]
Given that I am a developer for aricha.me, I should be able to use media query mixins with Sass to style my webpages for specific device screen sizes. 

Please use: 
* rem measurments for fonts
* the mixin format below for font sizes: 
```css
@mixin font-size($sizeValue: 1) {
    font-size: ($sizeValue * 16) * 1px;
    font-size: $sizeValue * 1 rem;
}
```
* the `@content` method for mixins, ex: 
```
@mixin small() {
    @media only screen and (max-width: 320px) {
        @content;
    }
}
``` 

### References
[Correct Way to do CSS breakpoints](https://medium.freecodecamp.org/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862)
